// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApp.Backend;

#nullable disable

namespace TodoApp.Backend.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20250830233009_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("TodoApp.Backend.Models.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("403b9af9-2341-4723-a434-6330fe7116bf"),
                            DueDate = new DateOnly(2026, 4, 30),
                            IsCompleted = false,
                            Title = "File taxes"
                        },
                        new
                        {
                            Id = new Guid("6d055426-cc5a-45b0-a4f5-1744454193a3"),
                            DueDate = new DateOnly(2024, 12, 25),
                            IsCompleted = true,
                            Title = "Go on vacation"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
